# label encoding
- label coding is the easiest encoding method
- it doesnot create a seperate column for each unique category but
- it just creates a single column where each category has its own numerical value

In [20]:
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('insurance_dataset.csv')
df.head()

   age bmi_category     sex     bmi  children smoker     region      charges
0   19       Normal    male  27.900         0    yes  northeast  16884.92400
1   23  Underweight  female  17.385         1     no  southeast   2775.19215
2   28        Obese  female  33.000         3     no  northwest   4449.46200
3   33       Normal  female  22.705         0     no  southeast  21984.47061
4   32   Overweight  female  28.880         0     no  southeast   3866.85520

In [21]:
# for a column where the the categories are not in order we cannot use ordinal encoding
# and for a column where we have multiple values like suppose bmi cateory we should not use one hot encoding 
#because one hot encoding will create seperate columns for categories like 'Normal , Obese, Overweight, Underweight'
# we can use label encoding for thaat
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['bmi_category_encoded']=encoder.fit_transform(df['bmi_category'])
df.head()

,age,bmi_category,sex,bmi,children,smoker,region,charges,bmi_category_encoded
0,19,Normal,male,27.900,0,yes,northeast,16884.92400,0
1,23,Underweight,female,17.385,1,no,southeast,2775.19215,3
2,28,Obese,female,33.000,3,no,northwest,4449.46200,1
3,33,Normal,female,22.705,0,no,southeast,21984.47061,0
4,32,Overweight,female,28.880,0,no,southeast,3866.85520,2

In [22]:
df=df.drop(['bmi_category'],axis=1)
df.head()

,age,sex,bmi,children,smoker,region,charges,bmi_category_encoded
0,19,male,27.900,0,yes,northeast,16884.92400,0
1,23,female,17.385,1,no,southeast,2775.19215,3
2,28,female,33.000,3,no,northwest,4449.46200,1
3,33,female,22.705,0,no,southeast,21984.47061,0
4,32,female,28.880,0,no,southeast,3866.85520,2