## Encoding Categorical Values
- machine learning models only work with numerical values
- those column with categorical(string dtype) should be converted to numerical data type
- for that we use Encoding
- ### Encodin is of two types
- one hot encoding
- ordinal encoding

# 1:Ordinal encoding
#### What it does: 
- Assigns a numeric rank (e.g., 0, 1, 2, 3) to categories based on their natural order or importance.

#### When to use: 
- When the categories have a clear, logical hierarchy (e.g., "Small" < "Medium" < "Large").

#### importance:
-  The numbers imply ordering but not equal spacing (e.g., the difference between 0→1 is not necessarily the same as 1→2).

In [36]:
import pandas as pd
df=pd.read_csv('insurance_dataset.csv')
df.head()

   age bmi_category     sex     bmi  children smoker     region      charges
0   19       Normal    male  27.900         0    yes  northeast  16884.92400
1   18        Obese  female  33.770         1     no  northwest   1725.55230
2   28        Obese  female  33.000         3     no  northwest   4449.46200
3   33       Normal  female  22.705         0     no  southeast  21984.47061
4   32   Overweight  female  28.880         0     no  southeast   3866.85520

In [37]:
#in the dataset the categorical columns are bmi_category,sex,smoker,region
#sex,smoker,region these columns needs one hot encoding because there is no hierarchy
#the bmi_cateory however needs ordinal encoding because the categories are in hierarchecal form
#one category is greater than the other and ...
# so here we will encode the bmi category with ordinal encoding

In [38]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[['Normal','Overweight','Obese','Underweight']])
df['bmi_categ_encoded']=encoder.fit_transform(df[['bmi_category']])
df.head() #we can see a new column 'bmi_categ_encoded' is added

,age,bmi_category,sex,bmi,children,smoker,region,charges,bmi_categ_encoded
0,19,Normal,male,27.900,0,yes,northeast,16884.92400,0.0
1,18,Obese,female,33.770,1,no,northwest,1725.55230,2.0
2,28,Obese,female,33.000,3,no,northwest,4449.46200,2.0
3,33,Normal,female,22.705,0,no,southeast,21984.47061,0.0
4,32,Overweight,female,28.880,0,no,southeast,3866.85520,1.0

In [39]:
# as we do not need the original bmi_category column we should drop it now
df=df.drop(['bmi_category'],axis=1)
df.head() #the bmi_category column is now removed

,age,sex,bmi,children,smoker,region,charges,bmi_categ_encoded
0,19,male,27.900,0,yes,northeast,16884.92400,0.0
1,18,female,33.770,1,no,northwest,1725.55230,2.0
2,28,female,33.000,3,no,northwest,4449.46200,2.0
3,33,female,22.705,0,no,southeast,21984.47061,0.0
4,32,female,28.880,0,no,southeast,3866.85520,1.0

# 2. One-Hot Encoding
#### What it does:
-  Creates a new binary column (0 or 1) for each unique category. For each row, only one of these columns gets a 1 (the category that applies), and the rest get 0.

#### When to use:
-  When the categories have no natural order (nominal data).

#### Important: 
- Avoids forcing a false ranking, but increases the number of columns.

In [40]:
# for encoding 'sex','region','smoker' we will use one hot encoding
df=pd.get_dummies(df,columns=['sex','region','smoker'],drop_first=False) #drop_first removes the original column
# this will create two binary encoded columns for sex as 'sex_male and sex_female'
# four binary encoded columns for region as 'region_northeast,region_northwest,region_southeast,region_southwest
#two binary encoded columns for smoker as smoker_yes and smoker_no
df.head()

,age,bmi,children,charges,bmi_categ_encoded,sex_female,sex_male,region_northeast,region_northwest,region_southeast,region_southwest,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,0.0,False,True,True,False,False,False,False,True
1,18,33.770,1,1725.55230,2.0,True,False,False,True,False,False,True,False
2,28,33.000,3,4449.46200,2.0,True,False,False,True,False,False,True,False
3,33,22.705,0,21984.47061,0.0,True,False,False,False,True,False,True,False
4,32,28.880,0,3866.85520,1.0,True,False,False,False,True,False,True,False

In [41]:

# also the smoker_yes column can tell us wether the person is smoker or not so we do not need the smoker_no column
# also the sex_male column can tell us wether male or female so do not need the sex_female column
df=df.drop(['sex_female','smoker_no'],axis=1)
df.head()

,age,bmi,children,charges,bmi_categ_encoded,sex_male,region_northeast,region_northwest,region_southeast,region_southwest,smoker_yes
0,19,27.900,0,16884.92400,0.0,True,True,False,False,False,True
1,18,33.770,1,1725.55230,2.0,False,False,True,False,False,False
2,28,33.000,3,4449.46200,2.0,False,False,True,False,False,False
3,33,22.705,0,21984.47061,0.0,False,False,False,True,False,False
4,32,28.880,0,3866.85520,1.0,False,False,False,True,False,False