In [19]:
import pandas as pd
df=pd.read_csv('./Mall_Customers - Mall_Customers.csv')
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

Feature Selection

I think only four ('Gender','Age','Annual Income (k$)','Spending Score (1-100)')  are suitable features for kmeans cause these can be efficient in classifying data to many clusters
ID column has notjing to do with classification

In [20]:
X=df[['Gender','Age','Annual Income (k$)','Spending Score (1-100)']]

Encoding Gendere
because it is string column and cannot be used directly in kmeans

In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['Gender']=le.fit_transform(X['Gender'])

Feature Scalling

In [22]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X['Annual Income (k$)']=scaler.fit_transform(X[['Annual Income (k$)']])
X['Spending Score (1-100)']=scaler.fit_transform(X[['Spending Score (1-100)']])
X.head()

   Gender  Age  Annual Income (k$)  Spending Score (1-100)
0       1   19           -1.738999               -0.434801
1       1   21           -1.738999                1.195704
2       0   20           -1.700830               -1.715913
3       0   23           -1.700830                1.040418
4       0   31           -1.662660               -0.395980

Checking for missing values

In [23]:
X.isna().sum()

Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

training model

In [24]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42, n_init=10)
X['Clusters'] = kmeans.fit_predict(X)

In [25]:
X.head() #checking if new column added or not

   Gender  Age  Annual Income (k$)  Spending Score (1-100)  Clusters
0       1   19           -1.738999               -0.434801         3
1       1   21           -1.738999                1.195704         3
2       0   20           -1.700830               -1.715913         3
3       0   23           -1.700830                1.040418         3
4       0   31           -1.662660               -0.395980         1

Figure Plot