## Functions
- map, apply and pipe
- these are some specific function we will be using in this notebook

### Loading dataset

In [31]:
import pandas as pd
df=pd.read_csv('ecommerce_dataset.csv')
# checking data set information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          23 non-null     int64
 1   order_date        23 non-null     str
 2   customer_id       23 non-null     int64
 3   product_category  23 non-null     str
 4   region            23 non-null     str
 5   quantity          23 non-null     int64
 6   unit_price        23 non-null     float64
 7   discount          23 non-null     float64
 8   payment_method    23 non-null     str
 9   delivery_type     23 non-null     int64
 10  customer_ratio    23 non-null     float64
dtypes: float64(3), int64(4), str(4)
memory usage: 2.1 KB

In [32]:
df.head(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_type,customer_ratio
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9
5,10006,1/6/2022,1071,Electronics,West,2,264.44,0.20,Card,3,3.3
6,10007,1/7/2022,1700,Clothing,South,6,564.60,0.23,Card,1,1.8
7,10008,1/8/2022,1020,Beauty,North,6,265.71,0.13,Card,2,3.7
8,10009,1/9/2022,1614,Clothing,South,6,224.65,0.27,Card,2,1.4
9,10010,1/10/2022,1121,Clothing,West,4,272.71,0.06,Card,10,4.5

## map Function

In [33]:
# suppose i want to create new column payment type which
# will store the method of of parment
# suppose i want the card and wallet to be both considered as digitall 
df['payment_type']=df['payment_method'].map(
    {
        "Card":"Digital",
        "Wallet":"Digital",
        "COD":"Cash"
    }
)

# cross checking with patment_method
df[['payment_method',"payment_type"]].head()

  payment_method payment_type
0         Wallet      Digital
1           Card      Digital
2            COD         Cash
3         Wallet      Digital
4         Wallet      Digital

In [34]:
# suppose i want to calculate how much payments were digital and how much cash
df.groupby('payment_type').size()

payment_type
Cash        7
Digital    16
dtype: int64

## Apply Function
- Apply function is used when more than one columns are invlved
#### used:
- To apply a function that doesn't exist in Pandas
- To transform data based on complex conditions
- To create new columns from existing ones
- syntax: df.apply(function, axis=0) or axis=1

In [35]:
# suppose i want to find total price of each product by multiplyin unit price with quantity
def total_price(row):
    return row["unit_price"]*row["quantity"]

# now i will apply the function to dataset
df['Total Amount']=df.apply(total_price,axis=1)
df.head(10) #now we have an extra column named Total Amount

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_type,customer_ratio,payment_type,Total Amount
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,Digital,2615.55
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,Digital,334.18
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,Cash,933.84
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,Digital,2622.35
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,Digital,699.35
5,10006,1/6/2022,1071,Electronics,West,2,264.44,0.20,Card,3,3.3,Digital,528.88
6,10007,1/7/2022,1700,Clothing,South,6,564.60,0.23,Card,1,1.8,Digital,3387.60
7,10008,1/8/2022,1020,Beauty,North,6,265.71,0.13,Card,2,3.7,Digital,1594.26
8,10009,1/9/2022,1614,Clothing,South,6,224.65,0.27,Card,2,1.4,Digital,1347.90
9,10010,1/10/2022,1121,Clothing,West,4,272.71,0.06,Card,10,4.5,Digital,1090.84

## pipe Function
The pipe() function allows you to chain multiple functions together in a clean, readable way. It's used for method chaining - applying a series of transformations to your data in sequence.
- syntax : df.pipe(function1).pipe(function2).pipe(function3)

In [ ]:
def add_total_price(df):
    """Function 1: Calculate total price for each order"""
    df['total_price'] = df['unit_price'] * df['quantity']
    return df

def add_net_price(df):
    """Function 2: Calculate net price after discount"""
    df['net_price'] = df['total_price'] * (1 - df['discount'])
    return df

def categorize_orders(df):
    """Function 3: Categorize orders based on net price"""
    df['order_category'] = df['net_price'].apply(
        lambda x: 'High' if x > 1000 else ('Medium' if x > 500 else 'Low')
    )
    return df

# Apply pipe with three functions
df= (df.pipe(add_total_price).pipe(add_net_price).pipe(categorize_orders))
df.head() #now we have total price, net price , order category

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_type,customer_ratio,payment_type,Total Amount,total_price,net_price,order_category
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,Digital,2615.55,2615.55,1883.1960,High
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,Digital,334.18,334.18,304.1038,Low
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,Cash,933.84,933.84,644.3496,Medium
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,Digital,2622.35,2622.35,2569.9030,High
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,Digital,699.35,699.35,468.5645,Low