In [12]:
import pandas as pd
df=pd.read_csv('ecommerce_dataset.csv')
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_type,customer_ratio
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9

- #### First i need to find the total net price for each order

In [13]:
def add_total_price(df):
    """Function 1: Calculate total price for each order"""
    df['total_price'] = df['unit_price'] * df['quantity']
    return df

def add_net_price(df):
    """Function 2: Calculate net price after discount"""
    df['net_price'] = df['total_price'] * (1 - df['discount'])
    return df

df=(df.pipe(add_total_price).pipe(add_net_price))
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_type,customer_ratio,total_price,net_price
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,1883.1960
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,304.1038
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,644.3496
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2569.9030
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,468.5645

### creating Index as order_date on dataframe

In [14]:
# Convert order_date to datetime
df['order_date'] = pd.to_datetime(df['order_date'])
df_indexed=df.set_index("order_date")
df_indexed.head()

,order_id,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_type,customer_ratio,total_price,net_price
order_date,,,,,,,,,,,,
2022-01-01,10001,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,1883.1960
2022-01-02,10002,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,304.1038
2022-01-03,10003,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,644.3496
2022-01-04,10004,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2569.9030
2022-01-05,10005,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,468.5645

## calculating monthly revenue

In [15]:
# Group by month using resample
monthly_revenue = df_indexed['net_price'].resample('ME').sum()
print("\nMonthly Revenue:")
print(monthly_revenue)

Monthly Revenue:
order_date
2022-01-31    26940.1742
Freq: ME, Name: net_price, dtype: float64

## checking if monthly revenue is increasing month by month or not

In [16]:
monthly_revenue.index.is_monotonic_increasing

True